structure(list(url = "https://tmc.mooc.fi/api/v8/core/submissions/136", 
    status_code = 403L, headers = structure(list(server = "nginx/1.13.1", 
        date = "Fri, 24 Nov 2017 10:44:51 GMT", `content-type` = "application/json; charset=utf-8", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        `cache-control` = "no-cache", vary = "Origin", `x-xss-protection` = "1; mode=block", 
        `x-request-id` = "8014D112-D104-11E7-A822-446785C04B87", 
        `x-runtime` = "0.072333", `x-frame-options` = "SAMEORIGIN", 
        `x-content-type-options` = "nosniff", `x-rack-cors` = "miss; no-origin", 
        `x-powered-by` = "Phusion Passenger 5.0.26", status = "403 Forbidden", 
        `content-encoding` = "gzip"), .Names = c("server", "date", 
    "content-type", "transfer-encoding", "connection", "cache-control", 
    "vary", "x-xss-protection", "x-request-id", "x-runtime", 
    "x-frame-options", "x-content-type-options", "x-rack-cors", 
    "x-powered-by", "status", "content-encoding"), class = c("insensitive", 
    "list")), all_headers = list(structure(list(status = 403L, 
        version = "HTTP/1.1", headers = structure(list(server = "nginx/1.13.1", 
            date = "Fri, 24 Nov 2017 10:44:51 GMT", `content-type` = "application/json; charset=utf-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            `cache-control` = "no-cache", vary = "Origin", `x-xss-protection` = "1; mode=block", 
            `x-request-id` = "8014D112-D104-11E7-A822-446785C04B87", 
            `x-runtime` = "0.072333", `x-frame-options` = "SAMEORIGIN", 
            `x-content-type-options` = "nosniff", `x-rack-cors` = "miss; no-origin", 
            `x-powered-by` = "Phusion Passenger 5.0.26", status = "403 Forbidden", 
            `content-encoding` = "gzip"), .Names = c("server", 
        "date", "content-type", "transfer-encoding", "connection", 
        "cache-control", "vary", "x-xss-protection", "x-request-id", 
        "x-runtime", "x-frame-options", "x-content-type-options", 
        "x-rack-cors", "x-powered-by", "status", "content-encoding"
        ), class = c("insensitive", "list"))), .Names = c("status", 
    "version", "headers"))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), .Names = c("domain", 
    "flag", "path", "secure", "expiration", "name", "value"), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"errors\":[\"You are not authorized to access this page.\"]}"), 
    date = structure(1511520291, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = structure(c(0, 2.9e-05, 3.1e-05, 
    8.6e-05, 0.169261, 0.169335), .Names = c("redirect", "namelookup", 
    "connect", "pretransfer", "starttransfer", "total")), request = structure(list(
        method = "GET", url = "https://tmc.mooc.fi/api/v8/core/submissions/136", 
        headers = structure(c("application/json, text/xml, application/xml, */*", 
        "REDACTED"), .Names = c("Accept", "Authorization")), 
        fields = NULL, options = structure(list(useragent = "libcurl/7.47.0 r-curl/2.8.1 httr/1.3.1", 
            httpget = TRUE), .Names = c("useragent", "httpget"
        )), output = structure(list(), class = c("write_memory", 
        "write_function"))), .Names = c("method", "url", "headers", 
    "fields", "options", "output"), class = "request")), .Names = c("url", 
"status_code", "headers", "all_headers", "cookies", "content", 
"date", "times", "request"), class = "response")
